language: erlang

otp_release:
  - 22.1
  - 21.3
  - 20.2
  - 19.3
  - 18.3
  - 17.5
  - R16B03-1

branches:
  only:
    - master

before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3

script: "make travis"
