language: erlang

otp_release:
  - 20.2
  - 20.1
  - 20.1
  - 19.3
  - 19.2
  - 19.1
  - 19.0
  - 18.3
  - 18.2.1
  - 18.1
  - 18.0
  - 17.5
  - 17.4
  - 17.3
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01

branches:
  only:
    - master

before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3

script: "make travis"
